// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Segunda4F.Data;

#nullable disable

namespace Segunda4F.Migrations
{
    [DbContext(typeof(DirectorioDBContext))]
    [Migration("20260527224401_RelacionesPedidos")]
    partial class RelacionesPedidos
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Segunda4F.Data.Cliente", b =>
                {
                    b.Property<int>("IdCliente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCliente"));

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdCliente");

                    b.ToTable("Clientes");
                });

            modelBuilder.Entity("Segunda4F.Data.DetallePedido", b =>
                {
                    b.Property<int>("IdDetalle")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdDetalle"));

                    b.Property<int>("Cantidad")
                        .HasColumnType("int");

                    b.Property<int>("IdPedido")
                        .HasColumnType("int");

                    b.Property<int>("IdProducto")
                        .HasColumnType("int");

                    b.Property<decimal>("Subtotal")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("IdDetalle");

                    b.HasIndex("IdPedido");

                    b.HasIndex("IdProducto");

                    b.ToTable("DetallePedidos");
                });

            modelBuilder.Entity("Segunda4F.Data.Pedido", b =>
                {
                    b.Property<int>("IdPedido")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPedido"));

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdCliente")
                        .HasColumnType("int");

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("IdPedido");

                    b.HasIndex("IdCliente");

                    b.ToTable("Pedidos");
                });

            modelBuilder.Entity("Segunda4F.Data.Producto", b =>
                {
                    b.Property<int>("IdProducto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdProducto"));

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Disponible")
                        .HasColumnType("bit");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Precio")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("IdProducto");

                    b.ToTable("Productos");

                    b.HasData(
                        new
                        {
                            IdProducto = 1,
                            Categoria = "Ramen",
                            Descripcion = "Caldo cremoso con fideos, cerdo, huevo y cebollín.",
                            Disponible = true,
                            Nombre = "Ramen tonkotsu",
                            Precio = 180m
                        },
                        new
                        {
                            IdProducto = 2,
                            Categoria = "Sushi",
                            Descripcion = "Rollo con cangrejo, aguacate, pepino y ajonjolí.",
                            Disponible = true,
                            Nombre = "Sushi roll California",
                            Precio = 140m
                        },
                        new
                        {
                            IdProducto = 3,
                            Categoria = "Entradas",
                            Descripcion = "Empanadillas japonesas doradas con salsa de soya.",
                            Disponible = true,
                            Nombre = "Gyozas de cerdo",
                            Precio = 95m
                        },
                        new
                        {
                            IdProducto = 4,
                            Categoria = "Wok",
                            Descripcion = "Fideos salteados con camarón, cacahuate y salsa thai.",
                            Disponible = true,
                            Nombre = "Pad Thai de camarón",
                            Precio = 175m
                        },
                        new
                        {
                            IdProducto = 5,
                            Categoria = "Arroz",
                            Descripcion = "Arroz salteado con verduras, huevo y pollo.",
                            Disponible = true,
                            Nombre = "Arroz frito especial",
                            Precio = 130m
                        },
                        new
                        {
                            IdProducto = 6,
                            Categoria = "Bebidas",
                            Descripcion = "Bebida refrescante de té verde japonés.",
                            Disponible = true,
                            Nombre = "Té verde frío",
                            Precio = 45m
                        });
                });

            modelBuilder.Entity("Segunda4F.Data.DetallePedido", b =>
                {
                    b.HasOne("Segunda4F.Data.Pedido", "Pedido")
                        .WithMany("Detalles")
                        .HasForeignKey("IdPedido")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Segunda4F.Data.Producto", "Producto")
                        .WithMany("Detalles")
                        .HasForeignKey("IdProducto")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pedido");

                    b.Navigation("Producto");
                });

            modelBuilder.Entity("Segunda4F.Data.Pedido", b =>
                {
                    b.HasOne("Segunda4F.Data.Cliente", "Cliente")
                        .WithMany("Pedidos")
                        .HasForeignKey("IdCliente")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("Segunda4F.Data.Cliente", b =>
                {
                    b.Navigation("Pedidos");
                });

            modelBuilder.Entity("Segunda4F.Data.Pedido", b =>
                {
                    b.Navigation("Detalles");
                });

            modelBuilder.Entity("Segunda4F.Data.Producto", b =>
                {
                    b.Navigation("Detalles");
                });
#pragma warning restore 612, 618
        }
    }
}
